//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUDAPP.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MUDAPP.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Abbreviation:.
        /// </summary>
        internal static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About the application.
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support the project.
        /// </summary>
        internal static string Adblock {
            get {
                return ResourceManager.GetString("Adblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support the project. Turn off advertising in the application..
        /// </summary>
        internal static string AdblockAbout {
            get {
                return ResourceManager.GetString("AdblockAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ads:.
        /// </summary>
        internal static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analogues:.
        /// </summary>
        internal static string Analog {
            get {
                return ResourceManager.GetString("Analog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drilling Mud Reagent.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign In Microsoft Account.
        /// </summary>
        internal static string AuthenticationMicrosoft {
            get {
                return ResourceManager.GetString("AuthenticationMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup and data recovery.
        /// </summary>
        internal static string AuthenticationTitle {
            get {
                return ResourceManager.GetString("AuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Developer.
        /// </summary>
        internal static string AuthorApp {
            get {
                return ResourceManager.GetString("AuthorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Andrey Ovcharenko.
        /// </summary>
        internal static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorship.
        /// </summary>
        internal static string AuthorTitle {
            get {
                return ResourceManager.GetString("AuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while performing the operation. Perform the operation later or restart the application and retry the operation..
        /// </summary>
        internal static string BackupError {
            get {
                return ResourceManager.GetString("BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bit code:.
        /// </summary>
        internal static string BitCode {
            get {
                return ResourceManager.GetString("BitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code position:.
        /// </summary>
        internal static string BitCodeSerial {
            get {
                return ResourceManager.GetString("BitCodeSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #.
        /// </summary>
        internal static string BitCodeSerialHeader {
            get {
                return ResourceManager.GetString("BitCodeSerialHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code symbol:.
        /// </summary>
        internal static string BitCodeSymbol {
            get {
                return ResourceManager.GetString("BitCodeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code
        ///Symbol.
        /// </summary>
        internal static string BitCodeSymbolHeader {
            get {
                return ResourceManager.GetString("BitCodeSymbolHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the drill bit type, and in each of the four cells, the desired drill bit cipher symbol..
        /// </summary>
        internal static string BitDecodeHelp {
            get {
                return ResourceManager.GetString("BitDecodeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To decipher the drill bits code:.
        /// </summary>
        internal static string BitDecodeHelpTitle {
            get {
                return ResourceManager.GetString("BitDecodeHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bit type:.
        /// </summary>
        internal static string BitType {
            get {
                return ResourceManager.GetString("BitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body density, g/cm3:.
        /// </summary>
        internal static string BodyDropDensityBodyLabel {
            get {
                return ResourceManager.GetString("BodyDropDensityBodyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The density of the environment, g/cm3:.
        /// </summary>
        internal static string BodyDropDensityEnvironmentLabel {
            get {
                return ResourceManager.GetString("BodyDropDensityEnvironmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diameter Body, mm:.
        /// </summary>
        internal static string BodyDropDiameterBallLabel {
            get {
                return ResourceManager.GetString("BodyDropDiameterBallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance, m:.
        /// </summary>
        internal static string BodyDropDistanceLabel {
            get {
                return ResourceManager.GetString("BodyDropDistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body drop rate:.
        /// </summary>
        internal static string BodyDropFactorLabel {
            get {
                return ResourceManager.GetString("BodyDropFactorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на δ - body density, g/cm3.
        /// </summary>
        internal static string BodyDropFormulaDensityBody {
            get {
                return ResourceManager.GetString("BodyDropFormulaDensityBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Δ - density of the medium, g/cm3.
        /// </summary>
        internal static string BodyDropFormulaDensityEnvironment {
            get {
                return ResourceManager.GetString("BodyDropFormulaDensityEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на d - diameter of the spherical body, mm.
        /// </summary>
        internal static string BodyDropFormulaDiameterBall {
            get {
                return ResourceManager.GetString("BodyDropFormulaDiameterBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на K - coefficient.
        /// </summary>
        internal static string BodyDropFormulaFactor {
            get {
                return ResourceManager.GetString("BodyDropFormulaFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body drop speed, cm/sec:.
        /// </summary>
        internal static string BodyDropSpeedLabel {
            get {
                return ResourceManager.GetString("BodyDropSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body drop time, min.:.
        /// </summary>
        internal static string BodyDropTimeLabel {
            get {
                return ResourceManager.GetString("BodyDropTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculate.
        /// </summary>
        internal static string CalcButtonLab {
            get {
                return ResourceManager.GetString("CalcButtonLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cement.
        /// </summary>
        internal static string Cement {
            get {
                return ResourceManager.GetString("Cement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density, g/cm3:.
        /// </summary>
        internal static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base density:.
        /// </summary>
        internal static string DensityBaseLabel {
            get {
                return ResourceManager.GetString("DensityBaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base density.
        /// </summary>
        internal static string DensityBaseTitle {
            get {
                return ResourceManager.GetString("DensityBaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density, kg/m3:.
        /// </summary>
        internal static string DensityCalcLabel {
            get {
                return ResourceManager.GetString("DensityCalcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density:.
        /// </summary>
        internal static string DensityLabel {
            get {
                return ResourceManager.GetString("DensityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metod to correct density:.
        /// </summary>
        internal static string DensityMetodLabel {
            get {
                return ResourceManager.GetString("DensityMetodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density at a given temperature, kg/m3.
        /// </summary>
        internal static string DensityResultLabel {
            get {
                return ResourceManager.GetString("DensityResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density.
        /// </summary>
        internal static string DensityTitle {
            get {
                return ResourceManager.GetString("DensityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore the database from the copy.
        /// </summary>
        internal static string DownloadDB {
            get {
                return ResourceManager.GetString("DownloadDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restoring a database from a copy.
        /// </summary>
        internal static string DownloadedDB {
            get {
                return ResourceManager.GetString("DownloadedDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Elongation, %:.
        /// </summary>
        internal static string Elongation {
            get {
                return ResourceManager.GetString("Elongation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel:.
        /// </summary>
        internal static string EnergyLabel {
            get {
                return ResourceManager.GetString("EnergyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feature:.
        /// </summary>
        internal static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active editing mode!.
        /// </summary>
        internal static string FilterError {
            get {
                return ResourceManager.GetString("FilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter by Ø.
        /// </summary>
        internal static string FilterOD {
            get {
                return ResourceManager.GetString("FilterOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter by type.
        /// </summary>
        internal static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formula:.
        /// </summary>
        internal static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на coefficient of cavernosity (usually 1.05–1.4).
        /// </summary>
        internal static string FormulaCaverCoeff {
            get {
                return ResourceManager.GetString("FormulaCaverCoeff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the compressibility factor of the spacer (usually 1.02 - 1.05).
        /// </summary>
        internal static string FormulaCcomp {
            get {
                return ResourceManager.GetString("FormulaCcomp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The total mass of dry cement material (in tons) for the preparation of the required volume of cement slurry.
        /// </summary>
        internal static string FormulaCementTWAbout {
            get {
                return ResourceManager.GetString("FormulaCementTWAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The volume of cement slurry Vcs (in m3) is defined as the sum of the volume of the annular space in the annular space, the volume of the annular space between the borehole walls and the outer walls of the casing string, and taking into account the cavernousity coefficient..
        /// </summary>
        internal static string FormulaCementVolAbout {
            get {
                return ResourceManager.GetString("FormulaCementVolAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume of cement solution, in m3.
        /// </summary>
        internal static string FormulaCementVolume {
            get {
                return ResourceManager.GetString("FormulaCementVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The calculation of the number of components of the dry cement mix and liquid for its mixing is carried out taking into account the water-solid (water-cement) ratio recommended by the supplier and the optimum density of cement mortar, which is 1.85 g / cm3 for additive-free cement.
        /// </summary>
        internal static string FormulaCementWAbout {
            get {
                return ResourceManager.GetString("FormulaCementWAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dry cement loss ratio (usually 1.05).
        /// </summary>
        internal static string FormulaCLossCement {
            get {
                return ResourceManager.GetString("FormulaCLossCement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на water loss coefficient (usually 1.25).
        /// </summary>
        internal static string FormulaCLossWater {
            get {
                return ResourceManager.GetString("FormulaCLossWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на safety factor (usually 1.05).
        /// </summary>
        internal static string FormulaCoeffTS {
            get {
                return ResourceManager.GetString("FormulaCoeffTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The mass of components required for the preparation of 1 m3 of solution (in tons) is determined by the formulas.
        /// </summary>
        internal static string FormulaComponentWAbout {
            get {
                return ResourceManager.GetString("FormulaComponentWAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на water solid ratio.
        /// </summary>
        internal static string FormulaCWaterSolid {
            get {
                return ResourceManager.GetString("FormulaCWaterSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The values of the water-solid ratio are determined from the values of the density of the cement slurry and the density of the mixing fluid..
        /// </summary>
        internal static string FormulaCwsAbout {
            get {
                return ResourceManager.GetString("FormulaCwsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на density of mixing fluid, g/cm3 (if the modification of the properties of the cement slurry is not needed, then 1g/cm3).
        /// </summary>
        internal static string FormulaDFluid {
            get {
                return ResourceManager.GetString("FormulaDFluid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на outer Ø of the cemented casing, mm.
        /// </summary>
        internal static string FormulaDoutCasing {
            get {
                return ResourceManager.GetString("FormulaDoutCasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the density of cement slurry, g/cm3 (usually 1.85).
        /// </summary>
        internal static string FormulaDSlurry {
            get {
                return ResourceManager.GetString("FormulaDSlurry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на borehole diameter, mm.
        /// </summary>
        internal static string FormulaDwell {
            get {
                return ResourceManager.GetString("FormulaDwell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data is incorrect or missing!.
        /// </summary>
        internal static string FormulaError {
            get {
                return ResourceManager.GetString("FormulaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The total volume of the mixing fluid for the preparation of the required volume of cement slurry, m3.
        /// </summary>
        internal static string FormulaFluidTWAbout {
            get {
                return ResourceManager.GetString("FormulaFluidTWAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mass of grouting material, for preparation of 1 m3 of solution, t..
        /// </summary>
        internal static string FormulaGcem {
            get {
                return ResourceManager.GetString("FormulaGcem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mass of mixing fluid per 1m3 solution, t..
        /// </summary>
        internal static string FormulaGflu {
            get {
                return ResourceManager.GetString("FormulaGflu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The height of the cement Cup in the casing, m.
        /// </summary>
        internal static string FormulaHCP {
            get {
                return ResourceManager.GetString("FormulaHCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters of the cemented column.
        /// </summary>
        internal static string FormulaLabCasing {
            get {
                return ResourceManager.GetString("FormulaLabCasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters of the previous column.
        /// </summary>
        internal static string FormulaLabCasingPrev {
            get {
                return ResourceManager.GetString("FormulaLabCasingPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на length of the cemented casing, m.
        /// </summary>
        internal static string FormulaLCasing {
            get {
                return ResourceManager.GetString("FormulaLCasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на depth of descent of the previous column along the trunk, m.
        /// </summary>
        internal static string FormulaLPrevColumn {
            get {
                return ResourceManager.GetString("FormulaLPrevColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на outer Ø of the previous casing, mm.
        /// </summary>
        internal static string FormulaODPrevCasing {
            get {
                return ResourceManager.GetString("FormulaODPrevCasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на height of the lifting cement solution from the shoe of the previous casing on the trunk, m.
        /// </summary>
        internal static string FormulaPrevHCP {
            get {
                return ResourceManager.GetString("FormulaPrevHCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed calculation is carried out using the Rittinger formula:.
        /// </summary>
        internal static string FormulaRittingerAbout {
            get {
                return ResourceManager.GetString("FormulaRittingerAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The volume of spacer Vsp (in m3) is defined as the volume of the internal space of the cemented casing, taking into account the compression ratio of the propellant, the volume of the cement cup and the volume of pipelines connecting the cementing units to the cementing head..
        /// </summary>
        internal static string FormulaSpacerVAbout {
            get {
                return ResourceManager.GetString("FormulaSpacerVAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на thickness of the wall of the cemented casing, mm.
        /// </summary>
        internal static string FormulaTcasing {
            get {
                return ResourceManager.GetString("FormulaTcasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the total mass of dry grouting material, t..
        /// </summary>
        internal static string FormulaTGcem {
            get {
                return ResourceManager.GetString("FormulaTGcem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на total volume of mixing fluid, m3.
        /// </summary>
        internal static string FormulaTGflu {
            get {
                return ResourceManager.GetString("FormulaTGflu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на wall thickness of the previous casing, mm.
        /// </summary>
        internal static string FormulaTPrevCasing {
            get {
                return ResourceManager.GetString("FormulaTPrevCasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the volume of pipelines connecting cementing units with cementing head, m3, is assumed to be 0.5m3.
        /// </summary>
        internal static string FormulaVpline {
            get {
                return ResourceManager.GetString("FormulaVpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.00.
        /// </summary>
        internal static string FormulaZero {
            get {
                return ResourceManager.GetString("FormulaZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Function:.
        /// </summary>
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standards:.
        /// </summary>
        internal static string GOST {
            get {
                return ResourceManager.GetString("GOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grade:.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group:.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Abbreviation.
        /// </summary>
        internal static string HeaderAbbreviation {
            get {
                return ResourceManager.GetString("HeaderAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amt.
        /// </summary>
        internal static string HeaderAmt {
            get {
                return ResourceManager.GetString("HeaderAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analogues.
        /// </summary>
        internal static string HeaderAnalog {
            get {
                return ResourceManager.GetString("HeaderAnalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ø BHA, mm.
        /// </summary>
        internal static string HeaderBitOD {
            get {
                return ResourceManager.GetString("HeaderBitOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ø BHA, inch.
        /// </summary>
        internal static string HeaderBitODinch {
            get {
                return ResourceManager.GetString("HeaderBitODinch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string HeaderDescription {
            get {
                return ResourceManager.GetString("HeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feature.
        /// </summary>
        internal static string HeaderFeature {
            get {
                return ResourceManager.GetString("HeaderFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feature.
        /// </summary>
        internal static string HeaderFeature1 {
            get {
                return ResourceManager.GetString("HeaderFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Function.
        /// </summary>
        internal static string HeaderFunction {
            get {
                return ResourceManager.GetString("HeaderFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standards.
        /// </summary>
        internal static string HeaderGOST {
            get {
                return ResourceManager.GetString("HeaderGOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grade.
        /// </summary>
        internal static string HeaderGrade {
            get {
                return ResourceManager.GetString("HeaderGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group.
        /// </summary>
        internal static string HeaderGroup {
            get {
                return ResourceManager.GetString("HeaderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight,
        ///kg/m.
        /// </summary>
        internal static string HeaderMassM {
            get {
                return ResourceManager.GetString("HeaderMassM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mass,
        ///kg.
        /// </summary>
        internal static string HeaderMassPcs {
            get {
                return ResourceManager.GetString("HeaderMassPcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notes.
        /// </summary>
        internal static string HeaderNote {
            get {
                return ResourceManager.GetString("HeaderNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ø mm.
        /// </summary>
        internal static string HeaderODmm {
            get {
                return ResourceManager.GetString("HeaderODmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ø coupling,
        ///mm.
        /// </summary>
        internal static string HeaderODoutCoupling {
            get {
                return ResourceManager.GetString("HeaderODoutCoupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ø pipes,
        ///mm.
        /// </summary>
        internal static string HeaderODoutPipes {
            get {
                return ResourceManager.GetString("HeaderODoutPipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ø x t, mm.
        /// </summary>
        internal static string HeaderPipesName {
            get {
                return ResourceManager.GetString("HeaderPipesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drill Rig.
        /// </summary>
        internal static string HeaderRig {
            get {
                return ResourceManager.GetString("HeaderRig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string HeaderType {
            get {
                return ResourceManager.GetString("HeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type pipes.
        /// </summary>
        internal static string HeaderTypePipes {
            get {
                return ResourceManager.GetString("HeaderTypePipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Height, mm:.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Picture:.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на inch.
        /// </summary>
        internal static string inch {
            get {
                return ResourceManager.GetString("inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount:.
        /// </summary>
        internal static string labelAmt {
            get {
                return ResourceManager.GetString("labelAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flights, amt:.
        /// </summary>
        internal static string labelAmtTransport {
            get {
                return ResourceManager.GetString("labelAmtTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drilling rig:.
        /// </summary>
        internal static string labelRig {
            get {
                return ResourceManager.GetString("labelRig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        internal static string labVersion {
            get {
                return ResourceManager.GetString("labVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string LanguageEng {
            get {
                return ResourceManager.GetString("LanguageEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        internal static string LanguageRus {
            get {
                return ResourceManager.GetString("LanguageRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application language.
        /// </summary>
        internal static string LanguagesApp {
            get {
                return ResourceManager.GetString("LanguagesApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Application Language.
        /// </summary>
        internal static string LanguagesSelect {
            get {
                return ResourceManager.GetString("LanguagesSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length, mm:.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string LexisEng {
            get {
                return ResourceManager.GetString("LexisEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter definition.
        /// </summary>
        internal static string LexisEntry {
            get {
                return ResourceManager.GetString("LexisEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        internal static string LexisRus {
            get {
                return ResourceManager.GetString("LexisRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight, kg/m:.
        /// </summary>
        internal static string MassM {
            get {
                return ResourceManager.GetString("MassM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mass, kg:.
        /// </summary>
        internal static string MassPcs {
            get {
                return ResourceManager.GetString("MassPcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mass, tons.:.
        /// </summary>
        internal static string MassT {
            get {
                return ResourceManager.GetString("MassT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string messageAttention {
            get {
                return ResourceManager.GetString("messageAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to delete the item?.
        /// </summary>
        internal static string messageDelete {
            get {
                return ResourceManager.GetString("messageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!.
        /// </summary>
        internal static string messageError {
            get {
                return ResourceManager.GetString("messageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to exit this App?.
        /// </summary>
        internal static string messageExit {
            get {
                return ResourceManager.GetString("messageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing the language requires that MUDCatalog be restarted!.
        /// </summary>
        internal static string messageLanguage {
            get {
                return ResourceManager.GetString("messageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This entry already exists!.
        /// </summary>
        internal static string messageNewItem {
            get {
                return ResourceManager.GetString("messageNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No active recording!.
        /// </summary>
        internal static string messageNoActiveRecord {
            get {
                return ResourceManager.GetString("messageNoActiveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string messageOk {
            get {
                return ResourceManager.GetString("messageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Problem when authenticating!.
        /// </summary>
        internal static string messageProblemAuthenticating {
            get {
                return ResourceManager.GetString("messageProblemAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success!.
        /// </summary>
        internal static string messageSuccess {
            get {
                return ResourceManager.GetString("messageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You&apos;ve signed in to your Microsoft account!.
        /// </summary>
        internal static string messageSuccessAuthenticating {
            get {
                return ResourceManager.GetString("messageSuccessAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have restored the database from a backup copy!.
        /// </summary>
        internal static string messageSuccessDownload {
            get {
                return ResourceManager.GetString("messageSuccessDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have created a backup copy of the database!.
        /// </summary>
        internal static string messageSuccessUpload {
            get {
                return ResourceManager.GetString("messageSuccessUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm Action!.
        /// </summary>
        internal static string messageTitleAction {
            get {
                return ResourceManager.GetString("messageTitleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit App?.
        /// </summary>
        internal static string messageTitleExit {
            get {
                return ResourceManager.GetString("messageTitleExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string messageСancel {
            get {
                return ResourceManager.GetString("messageСancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на from the observed density at the base temperature to the desired.
        /// </summary>
        internal static string metricBaseLabel {
            get {
                return ResourceManager.GetString("metricBaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на from density at observed temperature to basic conditions.
        /// </summary>
        internal static string metricObservedLabel {
            get {
                return ResourceManager.GetString("metricObservedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mm.
        /// </summary>
        internal static string mm {
            get {
                return ResourceManager.GetString("mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to connect to your account!.
        /// </summary>
        internal static string NoConnected {
            get {
                return ResourceManager.GetString("NoConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notes:.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ø inside, mm:.
        /// </summary>
        internal static string ODinsPipes {
            get {
                return ResourceManager.GetString("ODinsPipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ø, mm:.
        /// </summary>
        internal static string ODmm {
            get {
                return ResourceManager.GetString("ODmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ø outside:.
        /// </summary>
        internal static string ODoutPipes {
            get {
                return ResourceManager.GetString("ODoutPipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ø pipe.
        /// </summary>
        internal static string ODoutPipes1 {
            get {
                return ResourceManager.GetString("ODoutPipes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application on other platforms.
        /// </summary>
        internal static string OSAbout {
            get {
                return ResourceManager.GetString("OSAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MUDCatalog in Google Play.
        /// </summary>
        internal static string OSAndroid {
            get {
                return ResourceManager.GetString("OSAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MUDCatalog in Microsoft Store.
        /// </summary>
        internal static string OSMicrosoft {
            get {
                return ResourceManager.GetString("OSMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This application does not collect or store any user information..
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Privacy.
        /// </summary>
        internal static string PrivacyApp {
            get {
                return ResourceManager.GetString("PrivacyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Privacy Statement.
        /// </summary>
        internal static string PrivacyStatement {
            get {
                return ResourceManager.GetString("PrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Professional Mode - includes the ability to edit, delete and add entries to directories; save a copy of the database in the cloud OneDrive; restore a database from a saved copy in the OneDrive cloud; synchronize the database with the application on other platforms; turn off advertising in the application..
        /// </summary>
        internal static string ProStateAbout {
            get {
                return ResourceManager.GetString("ProStateAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable Professional Mode.
        /// </summary>
        internal static string ProStateOn {
            get {
                return ResourceManager.GetString("ProStateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rate the app.
        /// </summary>
        internal static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Species of rocks:.
        /// </summary>
        internal static string RockSort {
            get {
                return ResourceManager.GetString("RockSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rock Group:.
        /// </summary>
        internal static string RockType {
            get {
                return ResourceManager.GetString("RockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string SearchBar {
            get {
                return ResourceManager.GetString("SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SettingsApp {
            get {
                return ResourceManager.GetString("SettingsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Strength, MPa:.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max Strength, MPa:.
        /// </summary>
        internal static string StrengthMax {
            get {
                return ResourceManager.GetString("StrengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min Strength, MPa:.
        /// </summary>
        internal static string StrengthMin {
            get {
                return ResourceManager.GetString("StrengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table Name:.
        /// </summary>
        internal static string TableSymbolLabel {
            get {
                return ResourceManager.GetString("TableSymbolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table Name.
        /// </summary>
        internal static string TableSymbolTitle {
            get {
                return ResourceManager.GetString("TableSymbolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base temperature, °С:.
        /// </summary>
        internal static string TempBaseCalcLabel {
            get {
                return ResourceManager.GetString("TempBaseCalcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base temperature:.
        /// </summary>
        internal static string TempBaseLabel {
            get {
                return ResourceManager.GetString("TempBaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base temperature.
        /// </summary>
        internal static string TempBaseTitle {
            get {
                return ResourceManager.GetString("TempBaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature, °С:.
        /// </summary>
        internal static string TempCalcLabel {
            get {
                return ResourceManager.GetString("TempCalcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature:.
        /// </summary>
        internal static string TempLabel {
            get {
                return ResourceManager.GetString("TempLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature.
        /// </summary>
        internal static string TempTitle {
            get {
                return ResourceManager.GetString("TempTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max tensile, MPa:.
        /// </summary>
        internal static string Tensile {
            get {
                return ResourceManager.GetString("Tensile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the application theme.
        /// </summary>
        internal static string ThemesApp {
            get {
                return ResourceManager.GetString("ThemesApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        internal static string ThemesDarkName {
            get {
                return ResourceManager.GetString("ThemesDarkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        internal static string ThemesLightName {
            get {
                return ResourceManager.GetString("ThemesLightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        internal static string ThemesOSName {
            get {
                return ResourceManager.GetString("ThemesOSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Equipment catalog.
        /// </summary>
        internal static string TitleAggregatGroup {
            get {
                return ResourceManager.GetString("TitleAggregatGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rock tool.
        /// </summary>
        internal static string TitleBit {
            get {
                return ResourceManager.GetString("TitleBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drill Bits Code Dictionary.
        /// </summary>
        internal static string TitleBitCode {
            get {
                return ResourceManager.GetString("TitleBitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deciphering the drill Bits code.
        /// </summary>
        internal static string TitleBitDecode {
            get {
                return ResourceManager.GetString("TitleBitDecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ROCK TOOL.
        /// </summary>
        internal static string TitleBitGroup {
            get {
                return ResourceManager.GetString("TitleBitGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ø of BHA elements.
        /// </summary>
        internal static string TitleBitOD {
            get {
                return ResourceManager.GetString("TitleBitOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spherical body drop time.
        /// </summary>
        internal static string TitleBodyDrop {
            get {
                return ResourceManager.GetString("TitleBodyDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculation of cementing materials.
        /// </summary>
        internal static string TitleCalcCement {
            get {
                return ResourceManager.GetString("TitleCalcCement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cement volume.
        /// </summary>
        internal static string TitleCalcCementVol {
            get {
                return ResourceManager.GetString("TitleCalcCementVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight of cement.
        /// </summary>
        internal static string TitleCalcCementWeight {
            get {
                return ResourceManager.GetString("TitleCalcCementWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DRILLING CALCULATIONS.
        /// </summary>
        internal static string TitleCalcGroup {
            get {
                return ResourceManager.GetString("TitleCalcGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spacer Volume.
        /// </summary>
        internal static string TitleCalcSpacerVol {
            get {
                return ResourceManager.GetString("TitleCalcSpacerVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transport and special equipment.
        /// </summary>
        internal static string TitleCar {
            get {
                return ResourceManager.GetString("TitleCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transport and special equipment Type.
        /// </summary>
        internal static string TitleCarType {
            get {
                return ResourceManager.GetString("TitleCarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coupling Catalogue.
        /// </summary>
        internal static string TitleCouplingCatalog {
            get {
                return ResourceManager.GetString("TitleCouplingCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Types of couplings and threads.
        /// </summary>
        internal static string TitleCouplingType {
            get {
                return ResourceManager.GetString("TitleCouplingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directional drilling.
        /// </summary>
        internal static string TitleDDrill {
            get {
                return ResourceManager.GetString("TitleDDrill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In development!.
        /// </summary>
        internal static string TitleDevelopment {
            get {
                return ResourceManager.GetString("TitleDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complete set of drilling rigs.
        /// </summary>
        internal static string TitleDrillRig {
            get {
                return ResourceManager.GetString("TitleDrillRig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Types of drilling rigs.
        /// </summary>
        internal static string TitleDrillRigType {
            get {
                return ResourceManager.GetString("TitleDrillRigType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of drive.
        /// </summary>
        internal static string TitleDriveType {
            get {
                return ResourceManager.GetString("TitleDriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Element Catalogue.
        /// </summary>
        internal static string TitleElementCatalog {
            get {
                return ResourceManager.GetString("TitleElementCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Element Groups.
        /// </summary>
        internal static string TitleElementGroup {
            get {
                return ResourceManager.GetString("TitleElementGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel.
        /// </summary>
        internal static string TitleEnergy {
            get {
                return ResourceManager.GetString("TitleEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FUEL.
        /// </summary>
        internal static string TitleEnergyGroup {
            get {
                return ResourceManager.GetString("TitleEnergyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuels groups.
        /// </summary>
        internal static string TitleEnergyType {
            get {
                return ResourceManager.GetString("TitleEnergyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel density.
        /// </summary>
        internal static string TitleFuelCalc {
            get {
                return ResourceManager.GetString("TitleFuelCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density calculation.
        /// </summary>
        internal static string TitleFuelDenCalc {
            get {
                return ResourceManager.GetString("TitleFuelDenCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density table.
        /// </summary>
        internal static string TitleFuelDenTable {
            get {
                return ResourceManager.GetString("TitleFuelDenTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel types.
        /// </summary>
        internal static string TitleFuelType {
            get {
                return ResourceManager.GetString("TitleFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English-Russian definition dictionary.
        /// </summary>
        internal static string TitleLexis {
            get {
                return ResourceManager.GetString("TitleLexis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        internal static string TitleMasterPage {
            get {
                return ResourceManager.GetString("TitleMasterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Muds and cements.
        /// </summary>
        internal static string TitleMudCatalog {
            get {
                return ResourceManager.GetString("TitleMudCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MUDS &amp; CEMENTS.
        /// </summary>
        internal static string TitleMudGroup {
            get {
                return ResourceManager.GetString("TitleMudGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Muds and cements Types.
        /// </summary>
        internal static string TitleMudType {
            get {
                return ResourceManager.GetString("TitleMudType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OTHER CATALOGUES.
        /// </summary>
        internal static string TitleOtherGroup {
            get {
                return ResourceManager.GetString("TitleOtherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pipe Assortment.
        /// </summary>
        internal static string TitlePipeCatalog {
            get {
                return ResourceManager.GetString("TitlePipeCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PIPES.
        /// </summary>
        internal static string TitlePipesGroup {
            get {
                return ResourceManager.GetString("TitlePipesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pipes Type.
        /// </summary>
        internal static string TitlePipeType {
            get {
                return ResourceManager.GetString("TitlePipeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EQUIPMENT.
        /// </summary>
        internal static string TitleRigGroup {
            get {
                return ResourceManager.GetString("TitleRigGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drill Rig Kit.
        /// </summary>
        internal static string TitleRigSet {
            get {
                return ResourceManager.GetString("TitleRigSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rock Type.
        /// </summary>
        internal static string TitleRock {
            get {
                return ResourceManager.GetString("TitleRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catalog of rocks.
        /// </summary>
        internal static string TitleRockCatalog {
            get {
                return ResourceManager.GetString("TitleRockCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Species.
        /// </summary>
        internal static string TitleRockRang {
            get {
                return ResourceManager.GetString("TitleRockRang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rock Group.
        /// </summary>
        internal static string TitleRockType {
            get {
                return ResourceManager.GetString("TitleRockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grade and groups of steel.
        /// </summary>
        internal static string TitleSteelCatalog {
            get {
                return ResourceManager.GetString("TitleSteelCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created with the help of employees of the technological department of Poltava Drilling Company LLC.
        /// </summary>
        internal static string TitleThanks {
            get {
                return ResourceManager.GetString("TitleThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Casing attachment.
        /// </summary>
        internal static string TitleTools {
            get {
                return ResourceManager.GetString("TitleTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Equipment groups.
        /// </summary>
        internal static string TitleUnitGroup {
            get {
                return ResourceManager.GetString("TitleUnitGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Types of equipment.
        /// </summary>
        internal static string TitleUnitType {
            get {
                return ResourceManager.GetString("TitleUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  tons.
        /// </summary>
        internal static string Tonn {
            get {
                return ResourceManager.GetString("Tonn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load capacity, tons.
        /// </summary>
        internal static string Tonnage {
            get {
                return ResourceManager.GetString("Tonnage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        internal static string ToolbarItemFilter {
            get {
                return ResourceManager.GetString("ToolbarItemFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type:.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type pipe:.
        /// </summary>
        internal static string TypePipes {
            get {
                return ResourceManager.GetString("TypePipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save a copy of the database.
        /// </summary>
        internal static string UploadDB {
            get {
                return ResourceManager.GetString("UploadDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The process of saving a copy of the database.
        /// </summary>
        internal static string UploadedDB {
            get {
                return ResourceManager.GetString("UploadedDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database Version:.
        /// </summary>
        internal static string VersionDB {
            get {
                return ResourceManager.GetString("VersionDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thnickess, mm:.
        /// </summary>
        internal static string Wall {
            get {
                return ResourceManager.GetString("Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project site.
        /// </summary>
        internal static string WebApp {
            get {
                return ResourceManager.GetString("WebApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width, mm:.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something&apos;s wrong? Let me know .
        /// </summary>
        internal static string WrongLabel {
            get {
                return ResourceManager.GetString("WrongLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In here.
        /// </summary>
        internal static string WrongLabelMail {
            get {
                return ResourceManager.GetString("WrongLabelMail", resourceCulture);
            }
        }
    }
}
