#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MUDAPP.Droid.Resource", IsApplication=true)]

namespace MUDAPP.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.1.0.11")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int splash_animation = 2130771968;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int accent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorAccent = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorPrimary = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int colorPrimaryDark = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int launcher_background = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int primary = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int primaryDark = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int splash_background = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int window_background = 2130837512;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int default_image_app = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int logo_image_app = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int splash_logo = 2130903043;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040001
			public const int sliding_tabs = 2130968577;
			
			// aapt resource value: 0x7F040000
			public const int SplashImageView = 2130968576;
			
			// aapt resource value: 0x7F040002
			public const int toolbar = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int SplashScreen = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Tabbar = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int Toolbar = 2131034114;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F060000
			public const int icon = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int icon_round = 2131099649;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int ApplicationName = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int ActionBar_nameText = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int AppCompatDialogStyle = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int MainTheme = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int MainTheme_Base = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int Theme_Transparent = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
